#!/usr/bin/env python3
"""Ingest ATO ruling summaries into cadena_knowledge database.

Reads from data/rulings/summaries/ (JSON files generated by generate_ruling_summaries.py)
and inserts into documents + rulings tables.

Usage:
  python3 scripts/ingest_ruling_summaries.py --type aid     # ATO IDs only
  python3 scripts/ingest_ruling_summaries.py --type full    # Full rulings only
  python3 scripts/ingest_ruling_summaries.py --type all     # Both
"""

import asyncio
import json
import os
import re
import asyncpg
from pathlib import Path

# ── Config ──────────────────────────────────────────────────────────────────
SUMMARIES_DIR = Path(__file__).resolve().parent.parent / "data" / "rulings" / "summaries"

DATABASE_URL = os.environ.get("DATABASE_URL_TAX") or os.environ.get("DATABASE_URL") or \
    "postgresql://postgres:postgres@localhost:5432/cadena_knowledge"

# ── Type mapping ────────────────────────────────────────────────────────────
TYPE_MAP = {
    "TR": "TR", "TD": "TD", "PCG": "PCG", "GSTR": "GSTR",
    "LCG": "LCG", "CR": "CR", "PR": "PR", "PS_LA": "PS_LA",
    "TA": "TA", "IT": "IT", "MT": "MT", "SGR": "SGR",
    "AID": "ATO_ID",  # ATO IDs use ATO_ID in DB enum
}
EXTRA_TYPES = {"LCR": "LCG"}  # Citations that alias

FILE_TYPE_MAP = {
    "PS_LA": "PS_LA",
    "PSLA": "PS_LA",
}
for k, v in TYPE_MAP.items():
    FILE_TYPE_MAP[k] = v

# Reverse map: DB type → prefix for related_provisions/display
TYPE_PREFIX = {v: k for k, v in TYPE_MAP.items()}
TYPE_PREFIX["ATO_ID"] = "AID"


def parse_summary_filename(stem: str) -> tuple[str, str, str] | None:
    """Parse summary filename -> (db_type, number_part, citation_str).
    AID_2001_1.json -> ('ATO_ID', '2001/1', 'AID 2001/1')
    TR_2024_1.json  -> ('TR', '2024/1', 'TR 2024/1')
    """
    parts = stem.split("_", 2) if "_" in stem else [stem]
    if not parts:
        return None
    prefix = parts[0]
    # Handle PS_LA prefix (file prefix has underscore)
    if stem.startswith("PS_LA_"):
        prefix = "PS_LA"
        parts = stem.split("_", 3)

    db_type = FILE_TYPE_MAP.get(prefix)
    if not db_type:
        return None

    if prefix == "PS_LA" and len(parts) >= 4:
        year, num = parts[2], parts[3]
    elif len(parts) >= 3:
        year, num = parts[1], parts[2]
    elif len(parts) >= 2:
        # Sequential format: IT_123
        year, num = "0", parts[1]
    else:
        return None

    # Parse number (strip .json etc)
    num = num.replace(".json", "").lstrip("0") or "0"
    display_prefix = "PS LA" if db_type == "PS_LA" else ("ATO ID" if db_type == "ATO_ID" else prefix)
    citation = f"{display_prefix} {year}/{num}"
    ref = f"{prefix}_{year}_{num}"
    return db_type, ref, citation


async def ingest_aid(summaries_dir: Path, batch_size: int = 200) -> dict:
    """Ingest all ATO ID summaries into DB."""
    conn = await asyncpg.connect(DATABASE_URL)
    try:
        aid_files = sorted(summaries_dir.glob("AID_*.json"))
        total = len(aid_files)
        inserted = skipped = errors = 0

        for i in range(0, total, batch_size):
            batch = aid_files[i:i + batch_size]
            async with conn.transaction():
                for f in batch:
                    try:
                        data = json.loads(f.read_text(encoding="utf-8"))
                        parsed = parse_summary_filename(f.stem)
                        if not parsed:
                            errors += 1
                            continue
                        db_type, ref, citation = parsed

                        # Check if already exists
                        exists = await conn.fetchval(
                            "SELECT 1 FROM documents WHERE reference = $1", ref
                        )
                        if exists:
                            skipped += 1
                            continue

                        full_text = data.get("full_text", "")
                        title = data.get("title", citation)
                        subject = data.get("subject", "")

                        # Build metadata from summary
                        metadata = {
                            "citation": citation,
                            "cases_referenced": data.get("cases_referenced", []),
                            "legislation_referenced": data.get("legislation_referenced", []),
                            "question": data.get("question", ""),
                            "summary": True,
                            "source": "regex_extraction",
                        }

                        doc_id = await conn.fetchval(
                            """INSERT INTO documents (doc_type, reference, title, content, metadata)
                               VALUES ('ruling', $1, $2, $3, $4::jsonb)
                               RETURNING id""",
                            ref, title, full_text, json.dumps(metadata),
                        )

                        # Extract year and number from ref
                        year = None
                        num = ""
                        m = re.match(r"^AID_(\d{4})_(\d+)$", ref)
                        if m:
                            year = int(m.group(1))
                            num = m.group(2).lstrip("0") or "0"

                        status = data.get("status", "Final")
                        db_status = "current" if status == "Final" else status.lower()

                        await conn.execute(
                            """INSERT INTO rulings (document_id, ruling_type, ruling_number, status, related_provisions)
                               VALUES ($1, $2, $3, $4, $5)""",
                            doc_id, db_type, f"{year}/{num}" if year else num,
                            db_status, data.get("legislation_referenced", []),
                        )
                        inserted += 1
                    except Exception as e:
                        print(f"  ERROR {f.name}: {e}")
                        errors += 1

            print(f"  Progress: {min(i + batch_size, total)}/{total} — "
                  f"{inserted} inserted, {skipped} skipped, {errors} errors")

        await conn.execute("COMMIT")
        return {"total": total, "inserted": inserted, "skipped": skipped, "errors": errors}
    finally:
        await conn.close()


async def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--type", choices=["aid", "full", "all"], default="aid")
    args = parser.parse_args()

    if args.type in ("aid", "all"):
        print(f"Ingesting ATO IDs from {SUMMARIES_DIR}...")
        result = await ingest_aid(SUMMARIES_DIR)
        print(f"  ATO IDs: {result['inserted']} inserted, "
              f"{result['skipped']} skipped, {result['errors']} errors")
        print(f"  Total: {result['total']} files")

    print("\nDone.")


if __name__ == "__main__":
    asyncio.run(main())